<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

//Get current store id
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$currentStoreId = $storeManager->getStore()->getId();

$reviewCollectionFactory = $objectManager->create('Magento\Review\Model\ResourceModel\Review\CollectionFactory')->create();

// Get reviews collection
$reviewsCollection = $reviewCollectionFactory->addFieldToSelect('*')
        ->addStoreFilter($currentStoreId)
        ->addStatusFilter(\Magento\Review\Model\Review::STATUS_APPROVED)
        ->setDateOrder()
        ->addRateVotes();

echo "<pre>";
print_r($reviewsCollection->getData());
echo "</pre>";

$dateFormat = $block->getDateFormat() ? : \IntlDateFormatter::SHORT;

if ($reviewsCollection && count($reviewsCollection) > 0) {
    foreach ($reviewsCollection AS $review) {
        echo $review->getTitle() . "<br/>";
        echo $review->getDetail() . "<br/>";
        echo $review->getNickname() . "<br/>";
        echo $block->formatDate($review->getCreatedAt(), $dateFormat) . "<br/>";

        // Display Average Rating of Review
        $countRatings = count($review->getRatingVotes());
        if ($countRatings > 0) {
            ?>
            <div class="review-ratings">
                <?php
                $allRatings = 0;
                foreach ($review->getRatingVotes() as $vote) {
                    $allRatings = $allRatings + $vote->getPercent();
                }
                $allRatingsAvg = $allRatings / $countRatings;
                ?>
                <div class="rating-summary">
                    <div class="rating-result" title="<?php echo $allRatingsAvg; ?>%">
                        <meta itemprop="worstRating" content = "1"/>
                        <meta itemprop="bestRating" content = "100"/>
                        <span style="width:<?php echo $allRatingsAvg; ?>%">
                            <span itemprop="ratingValue"><?php echo $allRatingsAvg; ?>%</span>
                        </span>
                    </div>
                </div>
            </div>
            <?php
        }
    }
}